In [56]:
import ast
import pandas as pd

In [57]:
# Read and drop unused column
df = pd.read_csv('highest_holywood_grossing_movies_with_wikidata.csv')
df = df.drop('Unnamed: 0', axis=1)
df.head()

,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License,wikidata_id
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13,http://www.wikidata.org/entity/Q24871
1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13,http://www.wikidata.org/entity/Q23781155
2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767,1636174514,2320250281,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13,http://www.wikidata.org/entity/Q3604746
3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-Dec-97,"['Drama', 'Romance']",3 hr 14 min,PG-13,http://www.wikidata.org/entity/Q44578
4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015,Walt Disney Studios Motion Pictures,245000000,247966675,936662225,1134647993,2071310218,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13,http://www.wikidata.org/entity/Q6074

In [58]:
# Flatten genre
def convert_to_list(genre: str):
    return ast.literal_eval(genre)
df['Genre'] = df['Genre'].apply(convert_to_list)
df = df.explode('Genre', ignore_index=True)
df.head()

,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License,wikidata_id
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Action,2 hr 42 min,PG-13,http://www.wikidata.org/entity/Q24871
1,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Adventure,2 hr 42 min,PG-13,http://www.wikidata.org/entity/Q24871
2,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Fantasy,2 hr 42 min,PG-13,http://www.wikidata.org/entity/Q24871
3,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Sci-Fi,2 hr 42 min,PG-13,http://www.wikidata.org/entity/Q24871
4,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,Action,3 hr 1 min,PG-13,http://www.wikidata.org/entity/Q23781155

In [59]:
# Convert running time to float minutes
def convert_time(time: str):
    hour_split = time.split(' hr')
    hour_str = hour_split[0].strip()
    if hour_split[1] == '':
        min_str = '0'
    else:
        rest = hour_split[1]
        min_str = rest.split(' min')[0][1:]
    return 60 * int(hour_str) + int(min_str)
df['Running Time'] = df['Running Time'].apply(convert_time)
df.head()

,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License,wikidata_id
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Action,162,PG-13,http://www.wikidata.org/entity/Q24871
1,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Adventure,162,PG-13,http://www.wikidata.org/entity/Q24871
2,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Fantasy,162,PG-13,http://www.wikidata.org/entity/Q24871
3,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Sci-Fi,162,PG-13,http://www.wikidata.org/entity/Q24871
4,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,Action,181,PG-13,http://www.wikidata.org/entity/Q23781155

In [ ]:
# Drop all anomalies
col = 'Budget (in $)'
mask = ~df[col].str.isnumeric()
df.loc[mask, col] = None
df[col] = df[col].astype('Int64')

In [61]:
col = 'Domestic Opening (in $)'
mask = ~df[col].str.isnumeric()
df.loc[mask, col] = None
df[col] = df[col].astype('Int64')

In [62]:
col = 'Distributor'
mask = (df[col].str.contains(',', na=False) | df[col].str.contains('\\$', na=False))
df[col].str.contains('$', na=False).value_counts()
df.loc[mask, col] = None

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3598 entries, 0 to 3597
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Title                       3598 non-null   object
 1   Movie Info                  3598 non-null   object
 2   Year                        3598 non-null   int64
 3   Distributor                 3519 non-null   object
 4   Budget (in $)               2844 non-null   Int64
 5   Domestic Opening (in $)     3497 non-null   Int64
 6   Domestic Sales (in $)       3598 non-null   int64
 7   International Sales (in $)  3598 non-null   int64
 8   World Wide Sales (in $)     3598 non-null   int64
 9   Release Date                3598 non-null   object
 10  Genre                       3598 non-null   object
 11  Running Time                3598 non-null   int64
 12  License                     3381 non-null   object
 13  wikidata_id                 3209 non-null   object
dtypes: Int64(2), int64(5), object(7)
memory usage: 400.7+ KB

In [ ]:
# Save df
df.to_csv('highest_holywood_grossing_movies_with_wikidata_preprocessed_3.csv', index=False)

In [44]:
df.head()

,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License,wikidata_id
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Action,162,PG-13,http://www.wikidata.org/entity/Q24871
1,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Adventure,162,PG-13,http://www.wikidata.org/entity/Q24871
2,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Fantasy,162,PG-13,http://www.wikidata.org/entity/Q24871
3,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,Sci-Fi,162,PG-13,http://www.wikidata.org/entity/Q24871
4,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,Action,181,PG-13,http://www.wikidata.org/entity/Q23781155

In [45]:
df[df['Year'] <= 1999]

,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License,wikidata_id
12,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-Dec-97,Drama,194,PG-13,http://www.wikidata.org/entity/Q44578
13,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-Dec-97,Romance,194,PG-13,http://www.wikidata.org/entity/Q44578
120,Jurassic Park,A pragmatic paleontologist touring an almost c...,1993,Universal Pictures,63000000,47026828,407185075,705953473,1113138548,11-Jun-93,Action,127,PG-13,http://www.wikidata.org/entity/Q167726
121,Jurassic Park,A pragmatic paleontologist touring an almost c...,1993,Universal Pictures,63000000,47026828,407185075,705953473,1113138548,11-Jun-93,Adventure,127,PG-13,http://www.wikidata.org/entity/Q167726
122,Jurassic Park,A pragmatic paleontologist touring an almost c...,1993,Universal Pictures,63000000,47026828,407185075,705953473,1113138548,11-Jun-93,Sci-Fi,127,PG-13,http://www.wikidata.org/entity/Q167726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,The First Wives Club,"Reunited by the death of a college friend, thr...",1996,Paramount Pictures,September 20 1996 (Domestic),18913411,105489203,76000000,181489203,10-May-06,Action,98,PG-13,http://www.wikidata.org/entity/Q913620
3564,The First Wives Club,"Reunited by the death of a college friend, thr...",1996,Paramount Pictures,September 20 1996 (Domestic),18913411,105489203,76000000,181489203,10-May-06,Adventure,98,PG-13,http://www.wikidata.org/entity/Q913620
3565,The First Wives Club,"Reunited by the death of a college friend, thr...",1996,Paramount Pictures,September 20 1996 (Domestic),18913411,105489203,76000000,181489203,10-May-06,Thriller,98,PG-13,http://www.wikidata.org/entity/Q913620
3572,Hot Shots!,A parody of Top Gun in which a talented but un...,1991,Twentieth Century Fox,26000000,10848182,69467617,111628547,181096164,31-Jul-91,Action,84,NaN,http://www.wikidata.org/entity/Q832105
3573,Hot Shots!,A parody of Top Gun in which a talented but un...,1991,Twentieth Century Fox,26000000,10848182,69467617,111628547,181096164,31-Jul-91,Comedy,84,NaN,http://www.wikidata.org/entity/Q832105

In [ ]:
mask = ~df['Budget (in $)'].str.isnumeric()
df.loc[mask, 'Budget (in $)'] = None

In [57]:
df['Budget (in $)']

0       237000000
1       237000000
2       237000000
3       237000000
4       356000000
          ...
3593     75000000
3594         None
3595         None
3596         None
3597         None
Name: Budget (in $), Length: 3598, dtype: object